import { AppConfig, hasAiSummaryEndpoint } from '../config';
import { Decision, Document, Project, Task, Update } from '../types';

export interface ProjectSummaryInput {
  project: Project;
  tasks: Task[];
  updates: Update[];
  decisions: Decision[];
  documents: Document[];
}

interface RemoteSummaryResponse {
  text?: string;
  summary?: string;
  note?: string;
}

function formatOpenTasks(tasks: Task[]) {
  const openTasks = tasks.filter(task => task.status !== 'done');
  if (openTasks.length === 0) return 'No open tasks.';

  return openTasks
    .map(task => `• ${task.title}${task.dueDate ? ` (due ${task.dueDate})` : ''}`)
    .join('\n');
}

export function buildLocalProjectSummary({ project, tasks, updates, decisions, documents }: ProjectSummaryInput) {
  const latestUpdate = updates[0];
  const openDecisions = decisions.filter(decision => decision.status !== 'decided');

  return [
    `${project.title} is ${project.status.replace('_', ' ')} and ${project.progress}% complete.`,
    `Next step: ${project.nextStep}`,
    latestUpdate ? `Latest update: ${latestUpdate.text}` : 'Latest update: none logged yet.',
    `Open tasks:\n${formatOpenTasks(tasks)}`,
    openDecisions.length > 0
      ? `Decisions needed: ${openDecisions.map(decision => decision.title).join(', ')}`
      : 'Decisions needed: none right now.',
    documents.length > 0
      ? `Documents on file: ${documents.map(document => document.title).join(', ')}`
      : 'Documents on file: none yet.',
  ].join('\n\n');
}

export async function generateProjectSummary(input: ProjectSummaryInput) {
  const fallbackSummary = buildLocalProjectSummary(input);

  if (!hasAiSummaryEndpoint) {
    return {
      source: 'local' as const,
      text: fallbackSummary,
      note: 'Add EXPO_PUBLIC_AI_SUMMARY_ENDPOINT to call your server-side OpenAI summary function.',
    };
  }

  const response = await fetch(AppConfig.aiSummaryEndpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      project: input.project,
      tasks: input.tasks,
      updates: input.updates,
      decisions: input.decisions,
      documents: input.documents,
      fallbackSummary,
    }),
  });

  if (!response.ok) {
    return {
      source: 'local' as const,
      text: fallbackSummary,
      note: `Summary endpoint failed (${response.status}). Showing local summary instead.`,
    };
  }

  const json = await response.json() as RemoteSummaryResponse;
  const text = json.text || json.summary || fallbackSummary;

  return {
    source: 'remote' as const,
    text,
    note: json.note || 'Generated by your server-side AI summary endpoint.',
  };
}
